# Generated by Django 5.0 on 2023-12-27 18:35

import check_constraint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=check_constraint.models.AnnotatedCheckConstraint(annotations={}, check=models.Q(('price__lt', models.F('mrp'))), name='apiapp_purchase_price_check'),
        ),
    ]
