# Generated by Django 5.0 on 2023-12-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_purchase_apiapp_purchase_price_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.customer')),
            ],
        ),
    ]
